# Generated by Django 5.2.2 on 2025-06-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocalParagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportes.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Autocarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_assentos', models.PositiveIntegerField(default=50)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportes.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lugares_disponiveis', models.PositiveIntegerField()),
                ('autocarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportes.autocarro')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='transportes.localparagem')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens', to='transportes.localparagem')),
            ],
        ),
    ]
